export const REDIS_KEYS = {
  TEMP_USER: "TEMP_USER",
  USER: "USER",
  POST: "POST",
  COMMENT: "COMMENT",
  MESSAGE: "MESSAGE",
  CHAT_LIST: "CHAT_LIST",
  CHAT: "CHAT",
  GLOBAL_SEARCH: "GLOBAL_SEARCH",
  CATEGORY: "CATEGORY",
  SUB_CATEGORY: "SUB_CATEGORY",
};
